---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project1admins
  namespace: project1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin1@github
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin2@github
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin3@github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project1devs
  namespace: project1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev1@github
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev2@github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project1viewers
  namespace: project1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: viewer1@github
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: viewer2@github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project2admins
  namespace: project2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin1@github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project2devs
  namespace: project2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev2@github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project2viewers
  namespace: project2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: viewer3@github
